// <auto-generated />
namespace CMSNachrichtModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewDB202427March : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewDB202427March));
        
        string IMigrationMetadata.Id
        {
            get { return "202403270105319_NewDB2024-27-March"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
